name:                sequitur
version:             0.2.1.0
github:              "msakai/haskell-sequitur"
license:             BSD-3-Clause
author:              "Masahiro Sakai"
maintainer:          "masahiro.sakai@gmail.com"
copyright:           "Copyright (c) 2024 Masahiro Sakai"

extra-doc-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Grammar-based compression algorithms SEQUITUR
category:            Formal Languages, Language, Natural Language Processing, NLP, Text, Compression

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/msakai/haskell-sequitur#readme>

flags:
  build-example-programs:
    description: Build example programs
    default: false
    manual: true

dependencies:
- base >= 4.7 && < 5
- containers >= 0.6.4.1 && < 0.7

language: Haskell2010

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - hashable >= 1.3.0.0 && < 1.5
  - hashtables >= 1.2.4.2 && < 1.4
  - primitive >= 0.7.3.0 && < 0.10
  other-extensions:
  - ConstraintKinds
  - CPP
  - DeriveGeneric
  - FlexibleInstances
  - LambdaCase
  - ScopedTypeVariables
  - TypeFamilies

tests:
  sequitur-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequitur
    - hspec >= 2.7.10 && < 2.12
    - QuickCheck >= 2.14.2 && < 2.15

executables:
  sequitur-demo:
    main:                Main.hs
    source-dirs:         app/demo
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sequitur
    - clock >= 0.8.3 && < 0.9
    - optparse-applicative >= 0.16.1.0 && < 0.19
    - text >= 1.2.4.1 && < 2.2
    when:
    - condition: flag(build-example-programs)
      then:
        buildable: true
      else:
        buildable: false

benchmarks:
  sequitur-bench:
    main:                Main.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -O2
    dependencies:
    - base
    - sequitur
    - criterion >= 1.5.13.0 && <1.7
    - QuickCheck >= 2.14.2 && < 2.15
    other-extensions:
    - BlockArguments
    - NumericUnderscores
    - TypeApplications
